### ISSUE TITLE
VoidLinux package requires a Powerkit release

### ISSUE THREAD

**Issue by imrn** [rodlie/powerdwarf#19]
https://github.com/void-linux/void-packages/issues/8093

Packaging request is submitted to voidlinux.
It is accepted. However, it needs a powerkit release.
Any ETA for it?

**Comment by rodlie** [comment]
Sorry for not responding, somehow this issue was lost in my inbox.

I will do a final 1.0.0 release soon.

**Comment by rodlie** [comment]
done
