### ISSUE TITLE
Support kernel check bypass

### ISSUE THREAD

**Issue by rodlie** [rodlie/powerdwarf#23]
in powerkit we check the actual kernel cmdline for a valid resume disk before allowing hibernation, on some systems this is not needed and will disable hibernation (#18). I do however want to keep the kernel check on as default since most systems I have tested don't work without, and we can't allow a system to go into hibernation without any way to restore the session, that's bad.

So I will add a checkbox in the config to bypass this feature. Since this is not a major change I will add this to 1.0.1.

**Comment by rodlie** [comment]
@FrostKnight :

Could you please test this version when you get the time: https://github.com/rodlie/powerkit/archive/deaa150057efbaa4e6de203a82bd042537792ea4.tar.gz

You will now have a new option under settings:
![bypass](https://user-images.githubusercontent.com/34516798/56464059-61bbcd80-63e1-11e9-9ce1-838af743b552.png)
Check this and powerkit will ignore /proc/cmdline (and should work as test1).

Btw, what kind of distro are you using?

**Comment by FrostKnight** [comment]
sadly, it gave an error when I installed it. and when I went to check the option it gave an error so I reverted.
Hyperbola, its arch based.
Hyperbola.info is the official website.

**Comment by rodlie** [comment]
Ok, I will test it on a free laptop, sometime tomorrow.

**Comment by FrostKnight** [comment]
Ah okay, well I appreciate your help. :)
The last version at least worked aka that last test one.

**Comment by rodlie** [comment]
Probably a small issue, I just don't have time to test it on real hardware at the moment. Just use test1 until fixed.

**Comment by FrostKnight** [comment]
That's fine, and yes I will. :)
