### ISSUE TITLE
Powerkit causes comp to shut down when you log in.

### ISSUE THREAD

**Issue by FrostKnight** [rodlie/powerdwarf#24]
critical battery being set to shutdown,for me seems to cause the whole thing to shutdown once logged in as I said in the title. At least in Lumina Desktop. I wonder why this happens though or, if its only an archlinux bug. 
I will check to see if this is the case.

**Comment by FrostKnight** [comment]
I should also add this ONLY happens when your computer isn't plugged in.  but it also affects XFCE as well. I dunno if this is an archlinux issue a Hyperbola issue or what, but its really odd.

**Comment by rodlie** [comment]
Strange, not something I'm able to replicate. Does this also happen when you select hibernate?

Are you running other power managers? (if you run XFCE you will probably have issues because of xfce-power-manager) Are D-Bus/upower working?

Critical battery is trigger if the battery percent is over 0 and under X (what you have in settings).

**Comment by FrostKnight** [comment]
This only happens when I first boot up the laptop and during the first minute I log in with powerkit enabled.  Once I have it charged for the first minute aka plugged in, the issue stops happening from what I remember.  It is hella weird. As for XFCE i had xfce's power manager on also.  But Lumina I did not. and this happens in your test version as well as your, stable version which I am using currently.  I suppose this could be an arch/lumina issue.   I will check dbus and upower if you would like. ps, dbus is on.

**Comment by rodlie** [comment]
I will install Arch on a free laptop sometime this week and try to find the issue.

**Comment by FrostKnight** [comment]
Thank you. I am not sure if its an arch issue, or a Hyperbola issue. (derivative of arch)

But yeah, check and let me know. :)

**Comment by dkiziridis** [comment]
Run `systemctl enable upower.service` to enable **Upower** service.

**Comment by FrostKnight** [comment]
> Run `systemctl enable upower.service` to enable **Upower** service.

That doesnt work with openrc. Sorry... but yeah, this issue is not really a problem for me at the moment.  I may just have it closed.  Because I am already asking a lot anyhow. ;)

It probably does happen, when powerkit is set a particular way when i boot up system, but I don't have powerkit set to that way anyhow, etc...

**Comment by rodlie** [comment]
upower will be an optional requirement in the next major version, I have already replaced most of the functionality in upower in powerkit directly.

**Comment by FrostKnight** [comment]
I know that you closed other issue, but if you had done it completely, would it have required consolekit/logind?  But regardless, see my last comment here:

https://github.com/rodlie/powerkit/issues/28#issuecomment-573685861

**Comment by FrostKnight** [comment]
See:  https://github.com/rodlie/powerkit/issues/29#issuecomment-649746803

I have lost interest for now.
