### ISSUE TITLE
make dbus optional

### ISSUE THREAD

**Issue by FrostKnight** [rodlie/powerdwarf#28]
I was wondering if you could do that for this and storage, so that I can use, shutdown, suspend, restart and hibernate on my laptop without dbus. 
also be able to monitor my battery life on that laptop as well, it is simplicity aka...

**Comment by rodlie** [comment]
Re-writing/re-implementing D-Bus is not on my TODO list...

Let's say yes, what needs to be done?

* UPower/UDisks/(ConsoleKit/logind)
  I would need to hook into them on library level, or even worse re-create them

If I do that I still just have a daemon, I would need some kind of IPC to communicate with the user space applications, with user/permission support......... *(you get the point, D-Bus)*

Let's say I write a new IPC.... Other applications would not be able to communicate with the "new" power daemon since they expect *.freedesktop.org on D-Bus.

All in all I would just be wasting time re-creating existing working software.


I'm not saying no, but someone would need come up with a better solution(?), or do the job for me.

**Comment by FrostKnight** [comment]
I will see if someone has a better solution as to how, if so, I will get back to you whether it can be done, differently, or otherwise.

I assume making this software took a while? my apologies if so... 

But yeah, I will get back to you aka, when I find someone who has a better solution or otherwise.

**Comment by rodlie** [comment]
I'm open for changes, but everything depends on D-Bus, especially if you want a "functional" desktop.

**Comment by FrostKnight** [comment]
> I'm open for changes, but everything depends on D-Bus, especially if you want a "functional" desktop.

I see, well rest assured, if I find a non-dbus option that is quick/effective, or if I can find someone who will do the job, I will let ya know.  I apologize if I seem ungrateful for the no dbus option for draco desktop, I am glad you did that.

And i do appreciate it btw.

Anyways, there may be someone who can do it and/or have an easy fix.

Aka, I knew a few people online.

**Comment by FrostKnight** [comment]
Actually I think I may have a slightly better idea, if you are interested...
Shutdown, Suspend, Hibernate, Restart.

I realize now, I don't really need powerkit's full functionality, would it be possible to do the above in draco desktop or a small app? As for the batter icon, I can probably use other options to make it work.

Is that idea any easier, no gui, just the bare essentials:

Shutdown, Suspend, Hibernate, Restart, nothing else? 

Can this be closed in favor of something like this? if not, let me know and I will see if I can make something myself. I know someone who could possibly help.

**Comment by FrostKnight** [comment]
Appreciated, is there a command i need to enter to make the qt4 part work? it gives the same error for some reason.
and yes, I do have qt4 installed.

**Comment by rodlie** [comment]
There is nothing to test, the commit only includes a server<=>client ipc example to be used instead of dbus in the future. Replacing D-Bus will take a while.

First I need to replace UPower, I have started, but I don't know when I'm done.

**Comment by FrostKnight** [comment]
Ah, okay, thank you! my bad... I thought it was finished, let me know when it is. I will wait patiently till you reply.

**Comment by FrostKnight** [comment]
Sorry to reply again, but how are things going? curious is all. It has been over a month right? just checking is all. 

Actually, I built it without dbus and it does seem to work, although when i load draco with powerkit it still cannot suspend, shutdown or hibernate.  But I am thankful to be honest it works at all. It does work with lumina right now, and that's fine for now.  Let me know if you plan to merge the dbus-free powerkit into Draco Desktop

EDIT: Nope actually just the indicator of how much battery life is there works, my bad.

**Comment by rodlie** [comment]
I don't have time to look into this until maybe end of month at the earliest. Re-writing an app just because someone don't like D-Bus is also not that interesting to me, so low priority. This is however something I would like to experiment with, but that's for a later version down the line.

 It also seems you have moved on to [Lumina](https://github.com/lumina-desktop/lumina/issues/714), so I will close this.

**Comment by FrostKnight** [comment]
Yeah, I am sorry, I didn't say anything sooner, I just thought I might have been overpressuring you.  
I thought it would be easier to ask Lumina-Desktop given that Lumina and Draco are similiar, but without the issues of say, driving you nuts, to get it to work.

**Comment by FrostKnight** [comment]
Should I instead ask for one that works just for bsd and leave the whole, powerkit thing that you do for linux?

**Comment by FrostKnight** [comment]
> I don't have time to look into this until maybe end of month at the earliest. Re-writing an app just because someone don't like D-Bus is also not that interesting to me, so low priority. This is however something I would like to experiment with, but that's for a later version down the line.
> 
> It also seems you have moved on to [Lumina](https://github.com/lumina-desktop/lumina/issues/714), so I will close this.

Btw on that subject, I should clarify, this is why I am interested in BSD:

https://wiki.hyperbola.info/doku.php?id=en:main:nomenclatures

The part that says HyperbolaBSD.  anyways thanks for all that you have already done, I will just see if he can readd the functionality for poweroff, suspend, restart, hibernate. (logout and lock still work regardless)

**Comment by FrostKnight** [comment]
I should also add, consolekit/logind, dbus and upower all were the reason I thought lumina would have been a better way forward.  If you still feel like making these fixes feel free,cfor powerkit, not draco, I am in no hurry though, I can use powerkit till 2021 as is. After which, then I might need some fixes.  I apologize for not consulting with you about talking to the lumina people. They weren't too helpful. 

HyperbolaBSD is what I would need those changes for.  Anywho, have a lovely day when you read this. 

I do like Draco, but I also like Lumina. I use both, one on each of my comps.
