### ISSUE TITLE
Support backlight control through logind

### ISSUE THREAD

**Issue by Celti** [rodlie/powerdwarf#30]
As of systemd-243, [logind now exposes brightness controls through dbus](https://github.com/systemd/systemd/blob/master/NEWS#L882-L889) (since sysfs will likely never receive true ACL support). It would be nice if powerkit supported this alongside/instead of setting permissions via udev.

**Comment by rodlie** [comment]
I don't use systemd, but if you give me a link to the dbus spec for
backlight I can probably add it when I get the time.
