### ISSUE TITLE
Lock before suspend not working on Fedora

### ISSUE THREAD

**Issue by gion86** [rodlie/powerdwarf#32]
Hello,
I'm using Powerkit on Fedora 31, is working good, but lock on suspend doesn't work. I have:

- all the options set in powerkit setting, except "notify on battery" and "notify on AC"
- xscreensaver running

The suspend works, but the session isn't lock before the system goes to sleep.
Maybe something related to systemd? 
Thankyou.
Gionata

**Comment by rodlie** [comment]
Will check. I think this was fixed some time ago in the wip branch, was related to systemd on newer system.

**Comment by gion86** [comment]
I tried with the wip branch... nice graphic but.. none of the command works.. :)
Maybe is just a......work in progress..
