### ISSUE TITLE
Support for a custom locker command

### ISSUE THREAD

**Issue by gion86** [rodlie/powerdwarf#33]
I was thinking about using a different locker, like slock, it would be possible by adding a string widget in setting to le the user specify the command to be used for locking, and with some changes to the library and app?
Do you see any major problem in doing this? I might be able to make the changes and submit a pull request...

**Comment by rodlie** [comment]
Sure. Three commands are needed, one to start the lockapp, one to "ping" the lockapp (avoid locking) and one to lock the lockapp.

I can add the options sometime this week if I get the time.

Also note that I need to fix powerkit a bit, I merged powerkit-wip (aka powerkit2) with another project some time ago, and never put the changes back to powerkit.

**Comment by gion86** [comment]
OK, regarding slock for example the is just one command.. "slock" to start and lock. And the process blocks until a correct password is given. So this is a different case with respect to xscreensaver.

When you say 

> Also note that I need to fix powerkit a bit,

You mean the wip branch right?

**Comment by rodlie** [comment]
> When you say
> 
> > Also note that I need to fix powerkit a bit,
> 
> You mean the wip branch right?

Kind of, I "forked" the wip branch a while ago into https://github.com/rodlie/draco. I will need to figure out the best way to share the code between the two projects.

**Comment by rodlie** [comment]
v2 will have support for custom locker
