### ISSUE TITLE
Doesn't change HandleLidSwitch event

### ISSUE THREAD

**Issue by Ferryistaken** [rodlie/powerdwarf#34]
I use arch + bspwm, I have this in my bspwmrc:
```
killall -q powerkit; powerkit&
```
I ran `powerkit --configure` and configured it so that when I close the lid on AC power nothing happens, yet if I close the lid on AC power it goes to sleep. This is on a fresh arch install(I only installed basic utilities, and a WM). I use optimus-manager if that changes anything.

**Comment by rodlie** [comment]
#44
