### ISSUE TITLE
screen lock on lid close not working on slackware 15

### ISSUE THREAD

**Issue by giomatfois62** [rodlie/powerdwarf#37]
Hey, thanks for this little daemon, it seems to have a lot of features, I especially like the tab where you can see which applications are requisting an inhibition of the power management.  
One thing that i noticed is not working is automatic screen lock on lid close. It works fine using the testing button tough (the one on the bottom labeled "lock screen now").  
I saw in another posted issue that you moved to macos so probably you are not supporting this anymore, any chance you can take a look at this issue?

**Comment by rodlie** [comment]
Hi,

I have not tested Slackware 15, a lot of things may have changed since 14.2.

> I saw in another posted issue that you moved to macos so probably you are not supporting this anymore

I still have a Linux laptop, I'm not macOS exclusive.

I was actually planning on testing Slackware 15 soon-ish, so I will probably update powerkit when that happens.

**Comment by giomatfois62** [comment]
thank you very much, consider posting on LQ when you do a new release, lot of people appreciate your efforts

**Comment by rodlie** [comment]
Sorry for the delay, finally got around to install Slackware 15 on a laptop.

Screen lock works fine here with powerkit 1.0 (installed through slackbuilds), you will need to configure xscreensaver for this to work, as powerkit just triggers xscreensaver lock command (and don't know if xscreensaver actually does anything).

See ``man powerkit`` or https://github.com/rodlie/powerkit/tree/1.0#screen-saver for more information.
