### ISSUE TITLE
support change backlight for amdgpu

### ISSUE THREAD

**Issue by weipeng1999** [rodlie/powerdwarf#39]
thans for your work and the software works pretty well in my computer except I can not change my backlight.
After some work I got that some  sys file of amd gpu  is in /sys/class/backlight/amdgpu_bl0 and it same as radeon_bl0 in backlight, so i do following patch.  I wonder some guys may also face my problem, could you please check and merge these patches?
```
--- app/common.cpp	2022-04-06 16:06:02.203670414 +0800
+++ app/common.cpp	2022-04-06 16:07:28.080217463 +0800
@@ -184,6 +184,8 @@ QString Common::backlightDevice()
             return foundDir;
         } else if (foundDir.startsWith(QString("%1/acpi").arg(path))) {
             return foundDir;
+        } else if (foundDir.startsWith(QString("%1/amdgpu").arg(path))) {
+            return foundDir;
         }
     }
     return QString();
--- app/share/udev/90-backlight.rules	2019-04-05 03:17:22.000000000 +0800
+++ app/share/udev/90-backlight.rules	2022-04-06 15:55:20.798740845 +0800
@@ -4,3 +4,7 @@ ACTION=="add", SUBSYSTEM=="backlight", K
 ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="intel_backlight", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"
 ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="radeon_bl0", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
 ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="radeon_bl0", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"
+ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="amdgpu_bl0", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
+ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="amdgpu_bl0", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"
```

**Comment by rodlie** [comment]
Hi,

Thanks for your report, will check on Thursday or Friday.

*Also, feel free to do a pull request on the ``1.0`` branch if you want to.*

**Comment by maellis76** [comment]
Hi, I'm happy I found your software. The suspending and hibernating works great. I'm on Slackware 15 and running Fluxbox. However, I am experiencing an issue similar to this one where the controls for the backlighting are grayed out. Is there something I can do about that? Thank you.
